### ISSUE TITLE
Add unpack

### ISSUE THREAD

**Issue by adamdeller** [XhrisPhillips/gcorr#1]
The unpack method needs to be implemented.  I suggested that it operates on plain 2 bit real data with the headers already stripped out, and unpack directly into a complex float array (since otherwise we'll just have to convert the real floats to complex).

I'm hoping someone else will take this on, since I was going to focus initially on the fringe rotation.

**Comment by adamdeller** [comment]
Oh, and I was also assuming that it would be interleaved dual polarisation data, that would be de-interleaved in the unpacking process.  However, if we want to treat all inputs as single pol and deal with dual pol by treating them as separate antennas, that's also fine (albeit marginally less efficient, due to the duplication of parts of the fringe rotation, although if you ever end up with polarisation dependent clock offsets or anything then that efficiency is lost anyway).

**Comment by XhrisPhillips** [comment]
Done for 2bit 2 channel
